http:
  listener:
    host: "0.0.0.0"
    port: "9081"
    path: "/travelOnTipCall/{serviceType}"
    
db:
  mysql:
    host: "sql12.freesqldatabase.com"
    port: "3306"
    user: "sql12599649"
    pass: "jlLcmuQD5c"
    name: "sql12599649"